// Code generated by ent, DO NOT EDIT.

package yggdrasilnode

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/exepirit/yggmap/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldLTE(FieldID, id))
}

// PublicKey applies equality check predicate on the "publicKey" field. It's identical to PublicKeyEQ.
func PublicKey(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldEQ(FieldPublicKey, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldEQ(FieldAddress, v))
}

// Cluster applies equality check predicate on the "cluster" field. It's identical to ClusterEQ.
func Cluster(v int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldEQ(FieldCluster, v))
}

// PublicKeyEQ applies the EQ predicate on the "publicKey" field.
func PublicKeyEQ(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "publicKey" field.
func PublicKeyNEQ(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "publicKey" field.
func PublicKeyIn(vs ...string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "publicKey" field.
func PublicKeyNotIn(vs ...string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "publicKey" field.
func PublicKeyGT(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "publicKey" field.
func PublicKeyGTE(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "publicKey" field.
func PublicKeyLT(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "publicKey" field.
func PublicKeyLTE(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldLTE(FieldPublicKey, v))
}

// PublicKeyContains applies the Contains predicate on the "publicKey" field.
func PublicKeyContains(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldContains(FieldPublicKey, v))
}

// PublicKeyHasPrefix applies the HasPrefix predicate on the "publicKey" field.
func PublicKeyHasPrefix(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldHasPrefix(FieldPublicKey, v))
}

// PublicKeyHasSuffix applies the HasSuffix predicate on the "publicKey" field.
func PublicKeyHasSuffix(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldHasSuffix(FieldPublicKey, v))
}

// PublicKeyEqualFold applies the EqualFold predicate on the "publicKey" field.
func PublicKeyEqualFold(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldEqualFold(FieldPublicKey, v))
}

// PublicKeyContainsFold applies the ContainsFold predicate on the "publicKey" field.
func PublicKeyContainsFold(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldContainsFold(FieldPublicKey, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldContainsFold(FieldAddress, v))
}

// ClusterEQ applies the EQ predicate on the "cluster" field.
func ClusterEQ(v int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldEQ(FieldCluster, v))
}

// ClusterNEQ applies the NEQ predicate on the "cluster" field.
func ClusterNEQ(v int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldNEQ(FieldCluster, v))
}

// ClusterIn applies the In predicate on the "cluster" field.
func ClusterIn(vs ...int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldIn(FieldCluster, vs...))
}

// ClusterNotIn applies the NotIn predicate on the "cluster" field.
func ClusterNotIn(vs ...int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldNotIn(FieldCluster, vs...))
}

// ClusterGT applies the GT predicate on the "cluster" field.
func ClusterGT(v int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldGT(FieldCluster, v))
}

// ClusterGTE applies the GTE predicate on the "cluster" field.
func ClusterGTE(v int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldGTE(FieldCluster, v))
}

// ClusterLT applies the LT predicate on the "cluster" field.
func ClusterLT(v int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldLT(FieldCluster, v))
}

// ClusterLTE applies the LTE predicate on the "cluster" field.
func ClusterLTE(v int) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.FieldLTE(FieldCluster, v))
}

// HasNeighbors applies the HasEdge predicate on the "neighbors" edge.
func HasNeighbors() predicate.YggdrasilNode {
	return predicate.YggdrasilNode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, NeighborsTable, NeighborsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNeighborsWith applies the HasEdge predicate on the "neighbors" edge with a given conditions (other predicates).
func HasNeighborsWith(preds ...predicate.YggdrasilNode) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(func(s *sql.Selector) {
		step := newNeighborsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.YggdrasilNode) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.YggdrasilNode) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.YggdrasilNode) predicate.YggdrasilNode {
	return predicate.YggdrasilNode(sql.NotPredicates(p))
}
