// Code generated by ent, DO NOT EDIT.

package yggdrasilnode

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the yggdrasilnode type in the database.
	Label = "yggdrasil_node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPublicKey holds the string denoting the publickey field in the database.
	FieldPublicKey = "public_key"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldCluster holds the string denoting the cluster field in the database.
	FieldCluster = "cluster"
	// EdgeNeighbors holds the string denoting the neighbors edge name in mutations.
	EdgeNeighbors = "neighbors"
	// Table holds the table name of the yggdrasilnode in the database.
	Table = "yggdrasil_nodes"
	// NeighborsTable is the table that holds the neighbors relation/edge. The primary key declared below.
	NeighborsTable = "yggdrasil_node_neighbors"
)

// Columns holds all SQL columns for yggdrasilnode fields.
var Columns = []string{
	FieldID,
	FieldPublicKey,
	FieldAddress,
	FieldCluster,
}

var (
	// NeighborsPrimaryKey and NeighborsColumn2 are the table columns denoting the
	// primary key for the neighbors relation (M2M).
	NeighborsPrimaryKey = []string{"yggdrasil_node_id", "neighbor_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PublicKeyValidator is a validator for the "publicKey" field. It is called by the builders before save.
	PublicKeyValidator func(string) error
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
	// DefaultCluster holds the default value on creation for the "cluster" field.
	DefaultCluster int
)

// OrderOption defines the ordering options for the YggdrasilNode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPublicKey orders the results by the publicKey field.
func ByPublicKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicKey, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByCluster orders the results by the cluster field.
func ByCluster(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCluster, opts...).ToFunc()
}

// ByNeighborsCount orders the results by neighbors count.
func ByNeighborsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNeighborsStep(), opts...)
	}
}

// ByNeighbors orders the results by neighbors terms.
func ByNeighbors(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNeighborsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newNeighborsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, NeighborsTable, NeighborsPrimaryKey...),
	)
}
