// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/exepirit/yggmap/internal/data/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/exepirit/yggmap/internal/data/ent/yggdrasilnode"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// YggdrasilNode is the client for interacting with the YggdrasilNode builders.
	YggdrasilNode *YggdrasilNodeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.YggdrasilNode = NewYggdrasilNodeClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		YggdrasilNode: NewYggdrasilNodeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		YggdrasilNode: NewYggdrasilNodeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		YggdrasilNode.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.YggdrasilNode.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.YggdrasilNode.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *YggdrasilNodeMutation:
		return c.YggdrasilNode.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// YggdrasilNodeClient is a client for the YggdrasilNode schema.
type YggdrasilNodeClient struct {
	config
}

// NewYggdrasilNodeClient returns a client for the YggdrasilNode from the given config.
func NewYggdrasilNodeClient(c config) *YggdrasilNodeClient {
	return &YggdrasilNodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `yggdrasilnode.Hooks(f(g(h())))`.
func (c *YggdrasilNodeClient) Use(hooks ...Hook) {
	c.hooks.YggdrasilNode = append(c.hooks.YggdrasilNode, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `yggdrasilnode.Intercept(f(g(h())))`.
func (c *YggdrasilNodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.YggdrasilNode = append(c.inters.YggdrasilNode, interceptors...)
}

// Create returns a builder for creating a YggdrasilNode entity.
func (c *YggdrasilNodeClient) Create() *YggdrasilNodeCreate {
	mutation := newYggdrasilNodeMutation(c.config, OpCreate)
	return &YggdrasilNodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of YggdrasilNode entities.
func (c *YggdrasilNodeClient) CreateBulk(builders ...*YggdrasilNodeCreate) *YggdrasilNodeCreateBulk {
	return &YggdrasilNodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *YggdrasilNodeClient) MapCreateBulk(slice any, setFunc func(*YggdrasilNodeCreate, int)) *YggdrasilNodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &YggdrasilNodeCreateBulk{err: fmt.Errorf("calling to YggdrasilNodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*YggdrasilNodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &YggdrasilNodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for YggdrasilNode.
func (c *YggdrasilNodeClient) Update() *YggdrasilNodeUpdate {
	mutation := newYggdrasilNodeMutation(c.config, OpUpdate)
	return &YggdrasilNodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *YggdrasilNodeClient) UpdateOne(yn *YggdrasilNode) *YggdrasilNodeUpdateOne {
	mutation := newYggdrasilNodeMutation(c.config, OpUpdateOne, withYggdrasilNode(yn))
	return &YggdrasilNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *YggdrasilNodeClient) UpdateOneID(id int) *YggdrasilNodeUpdateOne {
	mutation := newYggdrasilNodeMutation(c.config, OpUpdateOne, withYggdrasilNodeID(id))
	return &YggdrasilNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for YggdrasilNode.
func (c *YggdrasilNodeClient) Delete() *YggdrasilNodeDelete {
	mutation := newYggdrasilNodeMutation(c.config, OpDelete)
	return &YggdrasilNodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *YggdrasilNodeClient) DeleteOne(yn *YggdrasilNode) *YggdrasilNodeDeleteOne {
	return c.DeleteOneID(yn.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *YggdrasilNodeClient) DeleteOneID(id int) *YggdrasilNodeDeleteOne {
	builder := c.Delete().Where(yggdrasilnode.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &YggdrasilNodeDeleteOne{builder}
}

// Query returns a query builder for YggdrasilNode.
func (c *YggdrasilNodeClient) Query() *YggdrasilNodeQuery {
	return &YggdrasilNodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeYggdrasilNode},
		inters: c.Interceptors(),
	}
}

// Get returns a YggdrasilNode entity by its id.
func (c *YggdrasilNodeClient) Get(ctx context.Context, id int) (*YggdrasilNode, error) {
	return c.Query().Where(yggdrasilnode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *YggdrasilNodeClient) GetX(ctx context.Context, id int) *YggdrasilNode {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNeighbors queries the neighbors edge of a YggdrasilNode.
func (c *YggdrasilNodeClient) QueryNeighbors(yn *YggdrasilNode) *YggdrasilNodeQuery {
	query := (&YggdrasilNodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := yn.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(yggdrasilnode.Table, yggdrasilnode.FieldID, id),
			sqlgraph.To(yggdrasilnode.Table, yggdrasilnode.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, yggdrasilnode.NeighborsTable, yggdrasilnode.NeighborsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(yn.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *YggdrasilNodeClient) Hooks() []Hook {
	return c.hooks.YggdrasilNode
}

// Interceptors returns the client interceptors.
func (c *YggdrasilNodeClient) Interceptors() []Interceptor {
	return c.inters.YggdrasilNode
}

func (c *YggdrasilNodeClient) mutate(ctx context.Context, m *YggdrasilNodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&YggdrasilNodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&YggdrasilNodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&YggdrasilNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&YggdrasilNodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown YggdrasilNode mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		YggdrasilNode []ent.Hook
	}
	inters struct {
		YggdrasilNode []ent.Interceptor
	}
)
