// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/exepirit/yggmap/internal/data/ent/predicate"
	"github.com/exepirit/yggmap/internal/data/ent/yggdrasilnode"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeYggdrasilNode = "YggdrasilNode"
)

// YggdrasilNodeMutation represents an operation that mutates the YggdrasilNode nodes in the graph.
type YggdrasilNodeMutation struct {
	config
	op               Op
	typ              string
	id               *int
	publicKey        *string
	address          *string
	cluster          *int
	addcluster       *int
	clearedFields    map[string]struct{}
	neighbors        map[int]struct{}
	removedneighbors map[int]struct{}
	clearedneighbors bool
	done             bool
	oldValue         func(context.Context) (*YggdrasilNode, error)
	predicates       []predicate.YggdrasilNode
}

var _ ent.Mutation = (*YggdrasilNodeMutation)(nil)

// yggdrasilnodeOption allows management of the mutation configuration using functional options.
type yggdrasilnodeOption func(*YggdrasilNodeMutation)

// newYggdrasilNodeMutation creates new mutation for the YggdrasilNode entity.
func newYggdrasilNodeMutation(c config, op Op, opts ...yggdrasilnodeOption) *YggdrasilNodeMutation {
	m := &YggdrasilNodeMutation{
		config:        c,
		op:            op,
		typ:           TypeYggdrasilNode,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withYggdrasilNodeID sets the ID field of the mutation.
func withYggdrasilNodeID(id int) yggdrasilnodeOption {
	return func(m *YggdrasilNodeMutation) {
		var (
			err   error
			once  sync.Once
			value *YggdrasilNode
		)
		m.oldValue = func(ctx context.Context) (*YggdrasilNode, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().YggdrasilNode.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withYggdrasilNode sets the old YggdrasilNode of the mutation.
func withYggdrasilNode(node *YggdrasilNode) yggdrasilnodeOption {
	return func(m *YggdrasilNodeMutation) {
		m.oldValue = func(context.Context) (*YggdrasilNode, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m YggdrasilNodeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m YggdrasilNodeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *YggdrasilNodeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *YggdrasilNodeMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().YggdrasilNode.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPublicKey sets the "publicKey" field.
func (m *YggdrasilNodeMutation) SetPublicKey(s string) {
	m.publicKey = &s
}

// PublicKey returns the value of the "publicKey" field in the mutation.
func (m *YggdrasilNodeMutation) PublicKey() (r string, exists bool) {
	v := m.publicKey
	if v == nil {
		return
	}
	return *v, true
}

// OldPublicKey returns the old "publicKey" field's value of the YggdrasilNode entity.
// If the YggdrasilNode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *YggdrasilNodeMutation) OldPublicKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPublicKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPublicKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPublicKey: %w", err)
	}
	return oldValue.PublicKey, nil
}

// ResetPublicKey resets all changes to the "publicKey" field.
func (m *YggdrasilNodeMutation) ResetPublicKey() {
	m.publicKey = nil
}

// SetAddress sets the "address" field.
func (m *YggdrasilNodeMutation) SetAddress(s string) {
	m.address = &s
}

// Address returns the value of the "address" field in the mutation.
func (m *YggdrasilNodeMutation) Address() (r string, exists bool) {
	v := m.address
	if v == nil {
		return
	}
	return *v, true
}

// OldAddress returns the old "address" field's value of the YggdrasilNode entity.
// If the YggdrasilNode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *YggdrasilNodeMutation) OldAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAddress: %w", err)
	}
	return oldValue.Address, nil
}

// ResetAddress resets all changes to the "address" field.
func (m *YggdrasilNodeMutation) ResetAddress() {
	m.address = nil
}

// SetCluster sets the "cluster" field.
func (m *YggdrasilNodeMutation) SetCluster(i int) {
	m.cluster = &i
	m.addcluster = nil
}

// Cluster returns the value of the "cluster" field in the mutation.
func (m *YggdrasilNodeMutation) Cluster() (r int, exists bool) {
	v := m.cluster
	if v == nil {
		return
	}
	return *v, true
}

// OldCluster returns the old "cluster" field's value of the YggdrasilNode entity.
// If the YggdrasilNode object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *YggdrasilNodeMutation) OldCluster(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCluster is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCluster requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCluster: %w", err)
	}
	return oldValue.Cluster, nil
}

// AddCluster adds i to the "cluster" field.
func (m *YggdrasilNodeMutation) AddCluster(i int) {
	if m.addcluster != nil {
		*m.addcluster += i
	} else {
		m.addcluster = &i
	}
}

// AddedCluster returns the value that was added to the "cluster" field in this mutation.
func (m *YggdrasilNodeMutation) AddedCluster() (r int, exists bool) {
	v := m.addcluster
	if v == nil {
		return
	}
	return *v, true
}

// ResetCluster resets all changes to the "cluster" field.
func (m *YggdrasilNodeMutation) ResetCluster() {
	m.cluster = nil
	m.addcluster = nil
}

// AddNeighborIDs adds the "neighbors" edge to the YggdrasilNode entity by ids.
func (m *YggdrasilNodeMutation) AddNeighborIDs(ids ...int) {
	if m.neighbors == nil {
		m.neighbors = make(map[int]struct{})
	}
	for i := range ids {
		m.neighbors[ids[i]] = struct{}{}
	}
}

// ClearNeighbors clears the "neighbors" edge to the YggdrasilNode entity.
func (m *YggdrasilNodeMutation) ClearNeighbors() {
	m.clearedneighbors = true
}

// NeighborsCleared reports if the "neighbors" edge to the YggdrasilNode entity was cleared.
func (m *YggdrasilNodeMutation) NeighborsCleared() bool {
	return m.clearedneighbors
}

// RemoveNeighborIDs removes the "neighbors" edge to the YggdrasilNode entity by IDs.
func (m *YggdrasilNodeMutation) RemoveNeighborIDs(ids ...int) {
	if m.removedneighbors == nil {
		m.removedneighbors = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.neighbors, ids[i])
		m.removedneighbors[ids[i]] = struct{}{}
	}
}

// RemovedNeighbors returns the removed IDs of the "neighbors" edge to the YggdrasilNode entity.
func (m *YggdrasilNodeMutation) RemovedNeighborsIDs() (ids []int) {
	for id := range m.removedneighbors {
		ids = append(ids, id)
	}
	return
}

// NeighborsIDs returns the "neighbors" edge IDs in the mutation.
func (m *YggdrasilNodeMutation) NeighborsIDs() (ids []int) {
	for id := range m.neighbors {
		ids = append(ids, id)
	}
	return
}

// ResetNeighbors resets all changes to the "neighbors" edge.
func (m *YggdrasilNodeMutation) ResetNeighbors() {
	m.neighbors = nil
	m.clearedneighbors = false
	m.removedneighbors = nil
}

// Where appends a list predicates to the YggdrasilNodeMutation builder.
func (m *YggdrasilNodeMutation) Where(ps ...predicate.YggdrasilNode) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the YggdrasilNodeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *YggdrasilNodeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.YggdrasilNode, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *YggdrasilNodeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *YggdrasilNodeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (YggdrasilNode).
func (m *YggdrasilNodeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *YggdrasilNodeMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.publicKey != nil {
		fields = append(fields, yggdrasilnode.FieldPublicKey)
	}
	if m.address != nil {
		fields = append(fields, yggdrasilnode.FieldAddress)
	}
	if m.cluster != nil {
		fields = append(fields, yggdrasilnode.FieldCluster)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *YggdrasilNodeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case yggdrasilnode.FieldPublicKey:
		return m.PublicKey()
	case yggdrasilnode.FieldAddress:
		return m.Address()
	case yggdrasilnode.FieldCluster:
		return m.Cluster()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *YggdrasilNodeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case yggdrasilnode.FieldPublicKey:
		return m.OldPublicKey(ctx)
	case yggdrasilnode.FieldAddress:
		return m.OldAddress(ctx)
	case yggdrasilnode.FieldCluster:
		return m.OldCluster(ctx)
	}
	return nil, fmt.Errorf("unknown YggdrasilNode field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *YggdrasilNodeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case yggdrasilnode.FieldPublicKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPublicKey(v)
		return nil
	case yggdrasilnode.FieldAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddress(v)
		return nil
	case yggdrasilnode.FieldCluster:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCluster(v)
		return nil
	}
	return fmt.Errorf("unknown YggdrasilNode field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *YggdrasilNodeMutation) AddedFields() []string {
	var fields []string
	if m.addcluster != nil {
		fields = append(fields, yggdrasilnode.FieldCluster)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *YggdrasilNodeMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case yggdrasilnode.FieldCluster:
		return m.AddedCluster()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *YggdrasilNodeMutation) AddField(name string, value ent.Value) error {
	switch name {
	case yggdrasilnode.FieldCluster:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCluster(v)
		return nil
	}
	return fmt.Errorf("unknown YggdrasilNode numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *YggdrasilNodeMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *YggdrasilNodeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *YggdrasilNodeMutation) ClearField(name string) error {
	return fmt.Errorf("unknown YggdrasilNode nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *YggdrasilNodeMutation) ResetField(name string) error {
	switch name {
	case yggdrasilnode.FieldPublicKey:
		m.ResetPublicKey()
		return nil
	case yggdrasilnode.FieldAddress:
		m.ResetAddress()
		return nil
	case yggdrasilnode.FieldCluster:
		m.ResetCluster()
		return nil
	}
	return fmt.Errorf("unknown YggdrasilNode field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *YggdrasilNodeMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.neighbors != nil {
		edges = append(edges, yggdrasilnode.EdgeNeighbors)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *YggdrasilNodeMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case yggdrasilnode.EdgeNeighbors:
		ids := make([]ent.Value, 0, len(m.neighbors))
		for id := range m.neighbors {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *YggdrasilNodeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedneighbors != nil {
		edges = append(edges, yggdrasilnode.EdgeNeighbors)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *YggdrasilNodeMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case yggdrasilnode.EdgeNeighbors:
		ids := make([]ent.Value, 0, len(m.removedneighbors))
		for id := range m.removedneighbors {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *YggdrasilNodeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedneighbors {
		edges = append(edges, yggdrasilnode.EdgeNeighbors)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *YggdrasilNodeMutation) EdgeCleared(name string) bool {
	switch name {
	case yggdrasilnode.EdgeNeighbors:
		return m.clearedneighbors
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *YggdrasilNodeMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown YggdrasilNode unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *YggdrasilNodeMutation) ResetEdge(name string) error {
	switch name {
	case yggdrasilnode.EdgeNeighbors:
		m.ResetNeighbors()
		return nil
	}
	return fmt.Errorf("unknown YggdrasilNode edge %s", name)
}
