// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/exepirit/yggmap/internal/data/ent/schema"
	"github.com/exepirit/yggmap/internal/data/ent/yggdrasilnode"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	yggdrasilnodeFields := schema.YggdrasilNode{}.Fields()
	_ = yggdrasilnodeFields
	// yggdrasilnodeDescPublicKey is the schema descriptor for publicKey field.
	yggdrasilnodeDescPublicKey := yggdrasilnodeFields[0].Descriptor()
	// yggdrasilnode.PublicKeyValidator is a validator for the "publicKey" field. It is called by the builders before save.
	yggdrasilnode.PublicKeyValidator = yggdrasilnodeDescPublicKey.Validators[0].(func(string) error)
	// yggdrasilnodeDescAddress is the schema descriptor for address field.
	yggdrasilnodeDescAddress := yggdrasilnodeFields[1].Descriptor()
	// yggdrasilnode.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	yggdrasilnode.AddressValidator = yggdrasilnodeDescAddress.Validators[0].(func(string) error)
	// yggdrasilnodeDescCluster is the schema descriptor for cluster field.
	yggdrasilnodeDescCluster := yggdrasilnodeFields[2].Descriptor()
	// yggdrasilnode.DefaultCluster holds the default value on creation for the cluster field.
	yggdrasilnode.DefaultCluster = yggdrasilnodeDescCluster.Default.(int)
}
