// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/exepirit/yggmap/internal/data/ent/predicate"
	"github.com/exepirit/yggmap/internal/data/ent/yggdrasilnode"
)

// YggdrasilNodeUpdate is the builder for updating YggdrasilNode entities.
type YggdrasilNodeUpdate struct {
	config
	hooks    []Hook
	mutation *YggdrasilNodeMutation
}

// Where appends a list predicates to the YggdrasilNodeUpdate builder.
func (ynu *YggdrasilNodeUpdate) Where(ps ...predicate.YggdrasilNode) *YggdrasilNodeUpdate {
	ynu.mutation.Where(ps...)
	return ynu
}

// AddNeighborIDs adds the "neighbors" edge to the YggdrasilNode entity by IDs.
func (ynu *YggdrasilNodeUpdate) AddNeighborIDs(ids ...int) *YggdrasilNodeUpdate {
	ynu.mutation.AddNeighborIDs(ids...)
	return ynu
}

// AddNeighbors adds the "neighbors" edges to the YggdrasilNode entity.
func (ynu *YggdrasilNodeUpdate) AddNeighbors(y ...*YggdrasilNode) *YggdrasilNodeUpdate {
	ids := make([]int, len(y))
	for i := range y {
		ids[i] = y[i].ID
	}
	return ynu.AddNeighborIDs(ids...)
}

// Mutation returns the YggdrasilNodeMutation object of the builder.
func (ynu *YggdrasilNodeUpdate) Mutation() *YggdrasilNodeMutation {
	return ynu.mutation
}

// ClearNeighbors clears all "neighbors" edges to the YggdrasilNode entity.
func (ynu *YggdrasilNodeUpdate) ClearNeighbors() *YggdrasilNodeUpdate {
	ynu.mutation.ClearNeighbors()
	return ynu
}

// RemoveNeighborIDs removes the "neighbors" edge to YggdrasilNode entities by IDs.
func (ynu *YggdrasilNodeUpdate) RemoveNeighborIDs(ids ...int) *YggdrasilNodeUpdate {
	ynu.mutation.RemoveNeighborIDs(ids...)
	return ynu
}

// RemoveNeighbors removes "neighbors" edges to YggdrasilNode entities.
func (ynu *YggdrasilNodeUpdate) RemoveNeighbors(y ...*YggdrasilNode) *YggdrasilNodeUpdate {
	ids := make([]int, len(y))
	for i := range y {
		ids[i] = y[i].ID
	}
	return ynu.RemoveNeighborIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ynu *YggdrasilNodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ynu.sqlSave, ynu.mutation, ynu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ynu *YggdrasilNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := ynu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ynu *YggdrasilNodeUpdate) Exec(ctx context.Context) error {
	_, err := ynu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ynu *YggdrasilNodeUpdate) ExecX(ctx context.Context) {
	if err := ynu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ynu *YggdrasilNodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(yggdrasilnode.Table, yggdrasilnode.Columns, sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt))
	if ps := ynu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if ynu.mutation.NeighborsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   yggdrasilnode.NeighborsTable,
			Columns: yggdrasilnode.NeighborsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ynu.mutation.RemovedNeighborsIDs(); len(nodes) > 0 && !ynu.mutation.NeighborsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   yggdrasilnode.NeighborsTable,
			Columns: yggdrasilnode.NeighborsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ynu.mutation.NeighborsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   yggdrasilnode.NeighborsTable,
			Columns: yggdrasilnode.NeighborsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ynu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{yggdrasilnode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ynu.mutation.done = true
	return n, nil
}

// YggdrasilNodeUpdateOne is the builder for updating a single YggdrasilNode entity.
type YggdrasilNodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *YggdrasilNodeMutation
}

// AddNeighborIDs adds the "neighbors" edge to the YggdrasilNode entity by IDs.
func (ynuo *YggdrasilNodeUpdateOne) AddNeighborIDs(ids ...int) *YggdrasilNodeUpdateOne {
	ynuo.mutation.AddNeighborIDs(ids...)
	return ynuo
}

// AddNeighbors adds the "neighbors" edges to the YggdrasilNode entity.
func (ynuo *YggdrasilNodeUpdateOne) AddNeighbors(y ...*YggdrasilNode) *YggdrasilNodeUpdateOne {
	ids := make([]int, len(y))
	for i := range y {
		ids[i] = y[i].ID
	}
	return ynuo.AddNeighborIDs(ids...)
}

// Mutation returns the YggdrasilNodeMutation object of the builder.
func (ynuo *YggdrasilNodeUpdateOne) Mutation() *YggdrasilNodeMutation {
	return ynuo.mutation
}

// ClearNeighbors clears all "neighbors" edges to the YggdrasilNode entity.
func (ynuo *YggdrasilNodeUpdateOne) ClearNeighbors() *YggdrasilNodeUpdateOne {
	ynuo.mutation.ClearNeighbors()
	return ynuo
}

// RemoveNeighborIDs removes the "neighbors" edge to YggdrasilNode entities by IDs.
func (ynuo *YggdrasilNodeUpdateOne) RemoveNeighborIDs(ids ...int) *YggdrasilNodeUpdateOne {
	ynuo.mutation.RemoveNeighborIDs(ids...)
	return ynuo
}

// RemoveNeighbors removes "neighbors" edges to YggdrasilNode entities.
func (ynuo *YggdrasilNodeUpdateOne) RemoveNeighbors(y ...*YggdrasilNode) *YggdrasilNodeUpdateOne {
	ids := make([]int, len(y))
	for i := range y {
		ids[i] = y[i].ID
	}
	return ynuo.RemoveNeighborIDs(ids...)
}

// Where appends a list predicates to the YggdrasilNodeUpdate builder.
func (ynuo *YggdrasilNodeUpdateOne) Where(ps ...predicate.YggdrasilNode) *YggdrasilNodeUpdateOne {
	ynuo.mutation.Where(ps...)
	return ynuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ynuo *YggdrasilNodeUpdateOne) Select(field string, fields ...string) *YggdrasilNodeUpdateOne {
	ynuo.fields = append([]string{field}, fields...)
	return ynuo
}

// Save executes the query and returns the updated YggdrasilNode entity.
func (ynuo *YggdrasilNodeUpdateOne) Save(ctx context.Context) (*YggdrasilNode, error) {
	return withHooks(ctx, ynuo.sqlSave, ynuo.mutation, ynuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ynuo *YggdrasilNodeUpdateOne) SaveX(ctx context.Context) *YggdrasilNode {
	node, err := ynuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ynuo *YggdrasilNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := ynuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ynuo *YggdrasilNodeUpdateOne) ExecX(ctx context.Context) {
	if err := ynuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ynuo *YggdrasilNodeUpdateOne) sqlSave(ctx context.Context) (_node *YggdrasilNode, err error) {
	_spec := sqlgraph.NewUpdateSpec(yggdrasilnode.Table, yggdrasilnode.Columns, sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt))
	id, ok := ynuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "YggdrasilNode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ynuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, yggdrasilnode.FieldID)
		for _, f := range fields {
			if !yggdrasilnode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != yggdrasilnode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ynuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if ynuo.mutation.NeighborsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   yggdrasilnode.NeighborsTable,
			Columns: yggdrasilnode.NeighborsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ynuo.mutation.RemovedNeighborsIDs(); len(nodes) > 0 && !ynuo.mutation.NeighborsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   yggdrasilnode.NeighborsTable,
			Columns: yggdrasilnode.NeighborsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ynuo.mutation.NeighborsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   yggdrasilnode.NeighborsTable,
			Columns: yggdrasilnode.NeighborsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &YggdrasilNode{config: ynuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ynuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{yggdrasilnode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ynuo.mutation.done = true
	return _node, nil
}
