// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/exepirit/yggmap/internal/data/ent/predicate"
	"github.com/exepirit/yggmap/internal/data/ent/yggdrasilnode"
)

// YggdrasilNodeDelete is the builder for deleting a YggdrasilNode entity.
type YggdrasilNodeDelete struct {
	config
	hooks    []Hook
	mutation *YggdrasilNodeMutation
}

// Where appends a list predicates to the YggdrasilNodeDelete builder.
func (ynd *YggdrasilNodeDelete) Where(ps ...predicate.YggdrasilNode) *YggdrasilNodeDelete {
	ynd.mutation.Where(ps...)
	return ynd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ynd *YggdrasilNodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ynd.sqlExec, ynd.mutation, ynd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ynd *YggdrasilNodeDelete) ExecX(ctx context.Context) int {
	n, err := ynd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ynd *YggdrasilNodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(yggdrasilnode.Table, sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt))
	if ps := ynd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ynd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ynd.mutation.done = true
	return affected, err
}

// YggdrasilNodeDeleteOne is the builder for deleting a single YggdrasilNode entity.
type YggdrasilNodeDeleteOne struct {
	ynd *YggdrasilNodeDelete
}

// Where appends a list predicates to the YggdrasilNodeDelete builder.
func (yndo *YggdrasilNodeDeleteOne) Where(ps ...predicate.YggdrasilNode) *YggdrasilNodeDeleteOne {
	yndo.ynd.mutation.Where(ps...)
	return yndo
}

// Exec executes the deletion query.
func (yndo *YggdrasilNodeDeleteOne) Exec(ctx context.Context) error {
	n, err := yndo.ynd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{yggdrasilnode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (yndo *YggdrasilNodeDeleteOne) ExecX(ctx context.Context) {
	if err := yndo.Exec(ctx); err != nil {
		panic(err)
	}
}
