// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/exepirit/yggmap/internal/data/ent/yggdrasilnode"
)

// YggdrasilNodeCreate is the builder for creating a YggdrasilNode entity.
type YggdrasilNodeCreate struct {
	config
	mutation *YggdrasilNodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPublicKey sets the "publicKey" field.
func (ync *YggdrasilNodeCreate) SetPublicKey(s string) *YggdrasilNodeCreate {
	ync.mutation.SetPublicKey(s)
	return ync
}

// SetAddress sets the "address" field.
func (ync *YggdrasilNodeCreate) SetAddress(s string) *YggdrasilNodeCreate {
	ync.mutation.SetAddress(s)
	return ync
}

// SetCluster sets the "cluster" field.
func (ync *YggdrasilNodeCreate) SetCluster(i int) *YggdrasilNodeCreate {
	ync.mutation.SetCluster(i)
	return ync
}

// SetNillableCluster sets the "cluster" field if the given value is not nil.
func (ync *YggdrasilNodeCreate) SetNillableCluster(i *int) *YggdrasilNodeCreate {
	if i != nil {
		ync.SetCluster(*i)
	}
	return ync
}

// AddNeighborIDs adds the "neighbors" edge to the YggdrasilNode entity by IDs.
func (ync *YggdrasilNodeCreate) AddNeighborIDs(ids ...int) *YggdrasilNodeCreate {
	ync.mutation.AddNeighborIDs(ids...)
	return ync
}

// AddNeighbors adds the "neighbors" edges to the YggdrasilNode entity.
func (ync *YggdrasilNodeCreate) AddNeighbors(y ...*YggdrasilNode) *YggdrasilNodeCreate {
	ids := make([]int, len(y))
	for i := range y {
		ids[i] = y[i].ID
	}
	return ync.AddNeighborIDs(ids...)
}

// Mutation returns the YggdrasilNodeMutation object of the builder.
func (ync *YggdrasilNodeCreate) Mutation() *YggdrasilNodeMutation {
	return ync.mutation
}

// Save creates the YggdrasilNode in the database.
func (ync *YggdrasilNodeCreate) Save(ctx context.Context) (*YggdrasilNode, error) {
	ync.defaults()
	return withHooks(ctx, ync.sqlSave, ync.mutation, ync.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ync *YggdrasilNodeCreate) SaveX(ctx context.Context) *YggdrasilNode {
	v, err := ync.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ync *YggdrasilNodeCreate) Exec(ctx context.Context) error {
	_, err := ync.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ync *YggdrasilNodeCreate) ExecX(ctx context.Context) {
	if err := ync.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ync *YggdrasilNodeCreate) defaults() {
	if _, ok := ync.mutation.Cluster(); !ok {
		v := yggdrasilnode.DefaultCluster
		ync.mutation.SetCluster(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ync *YggdrasilNodeCreate) check() error {
	if _, ok := ync.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "publicKey", err: errors.New(`ent: missing required field "YggdrasilNode.publicKey"`)}
	}
	if v, ok := ync.mutation.PublicKey(); ok {
		if err := yggdrasilnode.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "publicKey", err: fmt.Errorf(`ent: validator failed for field "YggdrasilNode.publicKey": %w`, err)}
		}
	}
	if _, ok := ync.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "YggdrasilNode.address"`)}
	}
	if v, ok := ync.mutation.Address(); ok {
		if err := yggdrasilnode.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "YggdrasilNode.address": %w`, err)}
		}
	}
	if _, ok := ync.mutation.Cluster(); !ok {
		return &ValidationError{Name: "cluster", err: errors.New(`ent: missing required field "YggdrasilNode.cluster"`)}
	}
	return nil
}

func (ync *YggdrasilNodeCreate) sqlSave(ctx context.Context) (*YggdrasilNode, error) {
	if err := ync.check(); err != nil {
		return nil, err
	}
	_node, _spec := ync.createSpec()
	if err := sqlgraph.CreateNode(ctx, ync.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ync.mutation.id = &_node.ID
	ync.mutation.done = true
	return _node, nil
}

func (ync *YggdrasilNodeCreate) createSpec() (*YggdrasilNode, *sqlgraph.CreateSpec) {
	var (
		_node = &YggdrasilNode{config: ync.config}
		_spec = sqlgraph.NewCreateSpec(yggdrasilnode.Table, sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt))
	)
	_spec.OnConflict = ync.conflict
	if value, ok := ync.mutation.PublicKey(); ok {
		_spec.SetField(yggdrasilnode.FieldPublicKey, field.TypeString, value)
		_node.PublicKey = value
	}
	if value, ok := ync.mutation.Address(); ok {
		_spec.SetField(yggdrasilnode.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := ync.mutation.Cluster(); ok {
		_spec.SetField(yggdrasilnode.FieldCluster, field.TypeInt, value)
		_node.Cluster = value
	}
	if nodes := ync.mutation.NeighborsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   yggdrasilnode.NeighborsTable,
			Columns: yggdrasilnode.NeighborsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.YggdrasilNode.Create().
//		SetPublicKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.YggdrasilNodeUpsert) {
//			SetPublicKey(v+v).
//		}).
//		Exec(ctx)
func (ync *YggdrasilNodeCreate) OnConflict(opts ...sql.ConflictOption) *YggdrasilNodeUpsertOne {
	ync.conflict = opts
	return &YggdrasilNodeUpsertOne{
		create: ync,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.YggdrasilNode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ync *YggdrasilNodeCreate) OnConflictColumns(columns ...string) *YggdrasilNodeUpsertOne {
	ync.conflict = append(ync.conflict, sql.ConflictColumns(columns...))
	return &YggdrasilNodeUpsertOne{
		create: ync,
	}
}

type (
	// YggdrasilNodeUpsertOne is the builder for "upsert"-ing
	//  one YggdrasilNode node.
	YggdrasilNodeUpsertOne struct {
		create *YggdrasilNodeCreate
	}

	// YggdrasilNodeUpsert is the "OnConflict" setter.
	YggdrasilNodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetCluster sets the "cluster" field.
func (u *YggdrasilNodeUpsert) SetCluster(v int) *YggdrasilNodeUpsert {
	u.Set(yggdrasilnode.FieldCluster, v)
	return u
}

// UpdateCluster sets the "cluster" field to the value that was provided on create.
func (u *YggdrasilNodeUpsert) UpdateCluster() *YggdrasilNodeUpsert {
	u.SetExcluded(yggdrasilnode.FieldCluster)
	return u
}

// AddCluster adds v to the "cluster" field.
func (u *YggdrasilNodeUpsert) AddCluster(v int) *YggdrasilNodeUpsert {
	u.Add(yggdrasilnode.FieldCluster, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.YggdrasilNode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *YggdrasilNodeUpsertOne) UpdateNewValues() *YggdrasilNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.PublicKey(); exists {
			s.SetIgnore(yggdrasilnode.FieldPublicKey)
		}
		if _, exists := u.create.mutation.Address(); exists {
			s.SetIgnore(yggdrasilnode.FieldAddress)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.YggdrasilNode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *YggdrasilNodeUpsertOne) Ignore() *YggdrasilNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *YggdrasilNodeUpsertOne) DoNothing() *YggdrasilNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the YggdrasilNodeCreate.OnConflict
// documentation for more info.
func (u *YggdrasilNodeUpsertOne) Update(set func(*YggdrasilNodeUpsert)) *YggdrasilNodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&YggdrasilNodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCluster sets the "cluster" field.
func (u *YggdrasilNodeUpsertOne) SetCluster(v int) *YggdrasilNodeUpsertOne {
	return u.Update(func(s *YggdrasilNodeUpsert) {
		s.SetCluster(v)
	})
}

// AddCluster adds v to the "cluster" field.
func (u *YggdrasilNodeUpsertOne) AddCluster(v int) *YggdrasilNodeUpsertOne {
	return u.Update(func(s *YggdrasilNodeUpsert) {
		s.AddCluster(v)
	})
}

// UpdateCluster sets the "cluster" field to the value that was provided on create.
func (u *YggdrasilNodeUpsertOne) UpdateCluster() *YggdrasilNodeUpsertOne {
	return u.Update(func(s *YggdrasilNodeUpsert) {
		s.UpdateCluster()
	})
}

// Exec executes the query.
func (u *YggdrasilNodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for YggdrasilNodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *YggdrasilNodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *YggdrasilNodeUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *YggdrasilNodeUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// YggdrasilNodeCreateBulk is the builder for creating many YggdrasilNode entities in bulk.
type YggdrasilNodeCreateBulk struct {
	config
	err      error
	builders []*YggdrasilNodeCreate
	conflict []sql.ConflictOption
}

// Save creates the YggdrasilNode entities in the database.
func (yncb *YggdrasilNodeCreateBulk) Save(ctx context.Context) ([]*YggdrasilNode, error) {
	if yncb.err != nil {
		return nil, yncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(yncb.builders))
	nodes := make([]*YggdrasilNode, len(yncb.builders))
	mutators := make([]Mutator, len(yncb.builders))
	for i := range yncb.builders {
		func(i int, root context.Context) {
			builder := yncb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*YggdrasilNodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, yncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = yncb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, yncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, yncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (yncb *YggdrasilNodeCreateBulk) SaveX(ctx context.Context) []*YggdrasilNode {
	v, err := yncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (yncb *YggdrasilNodeCreateBulk) Exec(ctx context.Context) error {
	_, err := yncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (yncb *YggdrasilNodeCreateBulk) ExecX(ctx context.Context) {
	if err := yncb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.YggdrasilNode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.YggdrasilNodeUpsert) {
//			SetPublicKey(v+v).
//		}).
//		Exec(ctx)
func (yncb *YggdrasilNodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *YggdrasilNodeUpsertBulk {
	yncb.conflict = opts
	return &YggdrasilNodeUpsertBulk{
		create: yncb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.YggdrasilNode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (yncb *YggdrasilNodeCreateBulk) OnConflictColumns(columns ...string) *YggdrasilNodeUpsertBulk {
	yncb.conflict = append(yncb.conflict, sql.ConflictColumns(columns...))
	return &YggdrasilNodeUpsertBulk{
		create: yncb,
	}
}

// YggdrasilNodeUpsertBulk is the builder for "upsert"-ing
// a bulk of YggdrasilNode nodes.
type YggdrasilNodeUpsertBulk struct {
	create *YggdrasilNodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.YggdrasilNode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *YggdrasilNodeUpsertBulk) UpdateNewValues() *YggdrasilNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.PublicKey(); exists {
				s.SetIgnore(yggdrasilnode.FieldPublicKey)
			}
			if _, exists := b.mutation.Address(); exists {
				s.SetIgnore(yggdrasilnode.FieldAddress)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.YggdrasilNode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *YggdrasilNodeUpsertBulk) Ignore() *YggdrasilNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *YggdrasilNodeUpsertBulk) DoNothing() *YggdrasilNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the YggdrasilNodeCreateBulk.OnConflict
// documentation for more info.
func (u *YggdrasilNodeUpsertBulk) Update(set func(*YggdrasilNodeUpsert)) *YggdrasilNodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&YggdrasilNodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCluster sets the "cluster" field.
func (u *YggdrasilNodeUpsertBulk) SetCluster(v int) *YggdrasilNodeUpsertBulk {
	return u.Update(func(s *YggdrasilNodeUpsert) {
		s.SetCluster(v)
	})
}

// AddCluster adds v to the "cluster" field.
func (u *YggdrasilNodeUpsertBulk) AddCluster(v int) *YggdrasilNodeUpsertBulk {
	return u.Update(func(s *YggdrasilNodeUpsert) {
		s.AddCluster(v)
	})
}

// UpdateCluster sets the "cluster" field to the value that was provided on create.
func (u *YggdrasilNodeUpsertBulk) UpdateCluster() *YggdrasilNodeUpsertBulk {
	return u.Update(func(s *YggdrasilNodeUpsert) {
		s.UpdateCluster()
	})
}

// Exec executes the query.
func (u *YggdrasilNodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the YggdrasilNodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for YggdrasilNodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *YggdrasilNodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
