// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/exepirit/yggmap/internal/data/ent/predicate"
	"github.com/exepirit/yggmap/internal/data/ent/yggdrasilnode"
)

// YggdrasilNodeQuery is the builder for querying YggdrasilNode entities.
type YggdrasilNodeQuery struct {
	config
	ctx           *QueryContext
	order         []yggdrasilnode.OrderOption
	inters        []Interceptor
	predicates    []predicate.YggdrasilNode
	withNeighbors *YggdrasilNodeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the YggdrasilNodeQuery builder.
func (ynq *YggdrasilNodeQuery) Where(ps ...predicate.YggdrasilNode) *YggdrasilNodeQuery {
	ynq.predicates = append(ynq.predicates, ps...)
	return ynq
}

// Limit the number of records to be returned by this query.
func (ynq *YggdrasilNodeQuery) Limit(limit int) *YggdrasilNodeQuery {
	ynq.ctx.Limit = &limit
	return ynq
}

// Offset to start from.
func (ynq *YggdrasilNodeQuery) Offset(offset int) *YggdrasilNodeQuery {
	ynq.ctx.Offset = &offset
	return ynq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ynq *YggdrasilNodeQuery) Unique(unique bool) *YggdrasilNodeQuery {
	ynq.ctx.Unique = &unique
	return ynq
}

// Order specifies how the records should be ordered.
func (ynq *YggdrasilNodeQuery) Order(o ...yggdrasilnode.OrderOption) *YggdrasilNodeQuery {
	ynq.order = append(ynq.order, o...)
	return ynq
}

// QueryNeighbors chains the current query on the "neighbors" edge.
func (ynq *YggdrasilNodeQuery) QueryNeighbors() *YggdrasilNodeQuery {
	query := (&YggdrasilNodeClient{config: ynq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ynq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ynq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(yggdrasilnode.Table, yggdrasilnode.FieldID, selector),
			sqlgraph.To(yggdrasilnode.Table, yggdrasilnode.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, yggdrasilnode.NeighborsTable, yggdrasilnode.NeighborsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(ynq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first YggdrasilNode entity from the query.
// Returns a *NotFoundError when no YggdrasilNode was found.
func (ynq *YggdrasilNodeQuery) First(ctx context.Context) (*YggdrasilNode, error) {
	nodes, err := ynq.Limit(1).All(setContextOp(ctx, ynq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{yggdrasilnode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ynq *YggdrasilNodeQuery) FirstX(ctx context.Context) *YggdrasilNode {
	node, err := ynq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first YggdrasilNode ID from the query.
// Returns a *NotFoundError when no YggdrasilNode ID was found.
func (ynq *YggdrasilNodeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ynq.Limit(1).IDs(setContextOp(ctx, ynq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{yggdrasilnode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ynq *YggdrasilNodeQuery) FirstIDX(ctx context.Context) int {
	id, err := ynq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single YggdrasilNode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one YggdrasilNode entity is found.
// Returns a *NotFoundError when no YggdrasilNode entities are found.
func (ynq *YggdrasilNodeQuery) Only(ctx context.Context) (*YggdrasilNode, error) {
	nodes, err := ynq.Limit(2).All(setContextOp(ctx, ynq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{yggdrasilnode.Label}
	default:
		return nil, &NotSingularError{yggdrasilnode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ynq *YggdrasilNodeQuery) OnlyX(ctx context.Context) *YggdrasilNode {
	node, err := ynq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only YggdrasilNode ID in the query.
// Returns a *NotSingularError when more than one YggdrasilNode ID is found.
// Returns a *NotFoundError when no entities are found.
func (ynq *YggdrasilNodeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ynq.Limit(2).IDs(setContextOp(ctx, ynq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{yggdrasilnode.Label}
	default:
		err = &NotSingularError{yggdrasilnode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ynq *YggdrasilNodeQuery) OnlyIDX(ctx context.Context) int {
	id, err := ynq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of YggdrasilNodes.
func (ynq *YggdrasilNodeQuery) All(ctx context.Context) ([]*YggdrasilNode, error) {
	ctx = setContextOp(ctx, ynq.ctx, ent.OpQueryAll)
	if err := ynq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*YggdrasilNode, *YggdrasilNodeQuery]()
	return withInterceptors[[]*YggdrasilNode](ctx, ynq, qr, ynq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ynq *YggdrasilNodeQuery) AllX(ctx context.Context) []*YggdrasilNode {
	nodes, err := ynq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of YggdrasilNode IDs.
func (ynq *YggdrasilNodeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ynq.ctx.Unique == nil && ynq.path != nil {
		ynq.Unique(true)
	}
	ctx = setContextOp(ctx, ynq.ctx, ent.OpQueryIDs)
	if err = ynq.Select(yggdrasilnode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ynq *YggdrasilNodeQuery) IDsX(ctx context.Context) []int {
	ids, err := ynq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ynq *YggdrasilNodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ynq.ctx, ent.OpQueryCount)
	if err := ynq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ynq, querierCount[*YggdrasilNodeQuery](), ynq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ynq *YggdrasilNodeQuery) CountX(ctx context.Context) int {
	count, err := ynq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ynq *YggdrasilNodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ynq.ctx, ent.OpQueryExist)
	switch _, err := ynq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ynq *YggdrasilNodeQuery) ExistX(ctx context.Context) bool {
	exist, err := ynq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the YggdrasilNodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ynq *YggdrasilNodeQuery) Clone() *YggdrasilNodeQuery {
	if ynq == nil {
		return nil
	}
	return &YggdrasilNodeQuery{
		config:        ynq.config,
		ctx:           ynq.ctx.Clone(),
		order:         append([]yggdrasilnode.OrderOption{}, ynq.order...),
		inters:        append([]Interceptor{}, ynq.inters...),
		predicates:    append([]predicate.YggdrasilNode{}, ynq.predicates...),
		withNeighbors: ynq.withNeighbors.Clone(),
		// clone intermediate query.
		sql:  ynq.sql.Clone(),
		path: ynq.path,
	}
}

// WithNeighbors tells the query-builder to eager-load the nodes that are connected to
// the "neighbors" edge. The optional arguments are used to configure the query builder of the edge.
func (ynq *YggdrasilNodeQuery) WithNeighbors(opts ...func(*YggdrasilNodeQuery)) *YggdrasilNodeQuery {
	query := (&YggdrasilNodeClient{config: ynq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ynq.withNeighbors = query
	return ynq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PublicKey string `json:"publicKey,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.YggdrasilNode.Query().
//		GroupBy(yggdrasilnode.FieldPublicKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ynq *YggdrasilNodeQuery) GroupBy(field string, fields ...string) *YggdrasilNodeGroupBy {
	ynq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &YggdrasilNodeGroupBy{build: ynq}
	grbuild.flds = &ynq.ctx.Fields
	grbuild.label = yggdrasilnode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PublicKey string `json:"publicKey,omitempty"`
//	}
//
//	client.YggdrasilNode.Query().
//		Select(yggdrasilnode.FieldPublicKey).
//		Scan(ctx, &v)
func (ynq *YggdrasilNodeQuery) Select(fields ...string) *YggdrasilNodeSelect {
	ynq.ctx.Fields = append(ynq.ctx.Fields, fields...)
	sbuild := &YggdrasilNodeSelect{YggdrasilNodeQuery: ynq}
	sbuild.label = yggdrasilnode.Label
	sbuild.flds, sbuild.scan = &ynq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a YggdrasilNodeSelect configured with the given aggregations.
func (ynq *YggdrasilNodeQuery) Aggregate(fns ...AggregateFunc) *YggdrasilNodeSelect {
	return ynq.Select().Aggregate(fns...)
}

func (ynq *YggdrasilNodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ynq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ynq); err != nil {
				return err
			}
		}
	}
	for _, f := range ynq.ctx.Fields {
		if !yggdrasilnode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ynq.path != nil {
		prev, err := ynq.path(ctx)
		if err != nil {
			return err
		}
		ynq.sql = prev
	}
	return nil
}

func (ynq *YggdrasilNodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*YggdrasilNode, error) {
	var (
		nodes       = []*YggdrasilNode{}
		_spec       = ynq.querySpec()
		loadedTypes = [1]bool{
			ynq.withNeighbors != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*YggdrasilNode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &YggdrasilNode{config: ynq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ynq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ynq.withNeighbors; query != nil {
		if err := ynq.loadNeighbors(ctx, query, nodes,
			func(n *YggdrasilNode) { n.Edges.Neighbors = []*YggdrasilNode{} },
			func(n *YggdrasilNode, e *YggdrasilNode) { n.Edges.Neighbors = append(n.Edges.Neighbors, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ynq *YggdrasilNodeQuery) loadNeighbors(ctx context.Context, query *YggdrasilNodeQuery, nodes []*YggdrasilNode, init func(*YggdrasilNode), assign func(*YggdrasilNode, *YggdrasilNode)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*YggdrasilNode)
	nids := make(map[int]map[*YggdrasilNode]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(yggdrasilnode.NeighborsTable)
		s.Join(joinT).On(s.C(yggdrasilnode.FieldID), joinT.C(yggdrasilnode.NeighborsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(yggdrasilnode.NeighborsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(yggdrasilnode.NeighborsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*YggdrasilNode]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*YggdrasilNode](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "neighbors" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (ynq *YggdrasilNodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ynq.querySpec()
	_spec.Node.Columns = ynq.ctx.Fields
	if len(ynq.ctx.Fields) > 0 {
		_spec.Unique = ynq.ctx.Unique != nil && *ynq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ynq.driver, _spec)
}

func (ynq *YggdrasilNodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(yggdrasilnode.Table, yggdrasilnode.Columns, sqlgraph.NewFieldSpec(yggdrasilnode.FieldID, field.TypeInt))
	_spec.From = ynq.sql
	if unique := ynq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ynq.path != nil {
		_spec.Unique = true
	}
	if fields := ynq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, yggdrasilnode.FieldID)
		for i := range fields {
			if fields[i] != yggdrasilnode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ynq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ynq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ynq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ynq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ynq *YggdrasilNodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ynq.driver.Dialect())
	t1 := builder.Table(yggdrasilnode.Table)
	columns := ynq.ctx.Fields
	if len(columns) == 0 {
		columns = yggdrasilnode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ynq.sql != nil {
		selector = ynq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ynq.ctx.Unique != nil && *ynq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ynq.predicates {
		p(selector)
	}
	for _, p := range ynq.order {
		p(selector)
	}
	if offset := ynq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ynq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// YggdrasilNodeGroupBy is the group-by builder for YggdrasilNode entities.
type YggdrasilNodeGroupBy struct {
	selector
	build *YggdrasilNodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (yngb *YggdrasilNodeGroupBy) Aggregate(fns ...AggregateFunc) *YggdrasilNodeGroupBy {
	yngb.fns = append(yngb.fns, fns...)
	return yngb
}

// Scan applies the selector query and scans the result into the given value.
func (yngb *YggdrasilNodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, yngb.build.ctx, ent.OpQueryGroupBy)
	if err := yngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*YggdrasilNodeQuery, *YggdrasilNodeGroupBy](ctx, yngb.build, yngb, yngb.build.inters, v)
}

func (yngb *YggdrasilNodeGroupBy) sqlScan(ctx context.Context, root *YggdrasilNodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(yngb.fns))
	for _, fn := range yngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*yngb.flds)+len(yngb.fns))
		for _, f := range *yngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*yngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := yngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// YggdrasilNodeSelect is the builder for selecting fields of YggdrasilNode entities.
type YggdrasilNodeSelect struct {
	*YggdrasilNodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (yns *YggdrasilNodeSelect) Aggregate(fns ...AggregateFunc) *YggdrasilNodeSelect {
	yns.fns = append(yns.fns, fns...)
	return yns
}

// Scan applies the selector query and scans the result into the given value.
func (yns *YggdrasilNodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, yns.ctx, ent.OpQuerySelect)
	if err := yns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*YggdrasilNodeQuery, *YggdrasilNodeSelect](ctx, yns.YggdrasilNodeQuery, yns, yns.inters, v)
}

func (yns *YggdrasilNodeSelect) sqlScan(ctx context.Context, root *YggdrasilNodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(yns.fns))
	for _, fn := range yns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*yns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := yns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
