// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/exepirit/yggmap/internal/data/ent/yggdrasilnode"
)

// YggdrasilNode is the model entity for the YggdrasilNode schema.
type YggdrasilNode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PublicKey holds the value of the "publicKey" field.
	PublicKey string `json:"publicKey,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the YggdrasilNodeQuery when eager-loading is set.
	Edges        YggdrasilNodeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// YggdrasilNodeEdges holds the relations/edges for other nodes in the graph.
type YggdrasilNodeEdges struct {
	// Neighbors holds the value of the neighbors edge.
	Neighbors []*YggdrasilNode `json:"neighbors,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NeighborsOrErr returns the Neighbors value or an error if the edge
// was not loaded in eager-loading.
func (e YggdrasilNodeEdges) NeighborsOrErr() ([]*YggdrasilNode, error) {
	if e.loadedTypes[0] {
		return e.Neighbors, nil
	}
	return nil, &NotLoadedError{edge: "neighbors"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*YggdrasilNode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case yggdrasilnode.FieldID:
			values[i] = new(sql.NullInt64)
		case yggdrasilnode.FieldPublicKey, yggdrasilnode.FieldAddress:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the YggdrasilNode fields.
func (yn *YggdrasilNode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case yggdrasilnode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			yn.ID = int(value.Int64)
		case yggdrasilnode.FieldPublicKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field publicKey", values[i])
			} else if value.Valid {
				yn.PublicKey = value.String
			}
		case yggdrasilnode.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				yn.Address = value.String
			}
		default:
			yn.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the YggdrasilNode.
// This includes values selected through modifiers, order, etc.
func (yn *YggdrasilNode) Value(name string) (ent.Value, error) {
	return yn.selectValues.Get(name)
}

// QueryNeighbors queries the "neighbors" edge of the YggdrasilNode entity.
func (yn *YggdrasilNode) QueryNeighbors() *YggdrasilNodeQuery {
	return NewYggdrasilNodeClient(yn.config).QueryNeighbors(yn)
}

// Update returns a builder for updating this YggdrasilNode.
// Note that you need to call YggdrasilNode.Unwrap() before calling this method if this YggdrasilNode
// was returned from a transaction, and the transaction was committed or rolled back.
func (yn *YggdrasilNode) Update() *YggdrasilNodeUpdateOne {
	return NewYggdrasilNodeClient(yn.config).UpdateOne(yn)
}

// Unwrap unwraps the YggdrasilNode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (yn *YggdrasilNode) Unwrap() *YggdrasilNode {
	_tx, ok := yn.config.driver.(*txDriver)
	if !ok {
		panic("ent: YggdrasilNode is not a transactional entity")
	}
	yn.config.driver = _tx.drv
	return yn
}

// String implements the fmt.Stringer.
func (yn *YggdrasilNode) String() string {
	var builder strings.Builder
	builder.WriteString("YggdrasilNode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", yn.ID))
	builder.WriteString("publicKey=")
	builder.WriteString(yn.PublicKey)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(yn.Address)
	builder.WriteByte(')')
	return builder.String()
}

// YggdrasilNodes is a parsable slice of YggdrasilNode.
type YggdrasilNodes []*YggdrasilNode
