// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// YggdrasilNode is the predicate function for yggdrasilnode builders.
type YggdrasilNode func(*sql.Selector)
