// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// YggdrasilNodesColumns holds the columns for the "yggdrasil_nodes" table.
	YggdrasilNodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "public_key", Type: field.TypeString, Unique: true},
		{Name: "address", Type: field.TypeString},
		{Name: "cluster", Type: field.TypeInt, Default: 0},
	}
	// YggdrasilNodesTable holds the schema information for the "yggdrasil_nodes" table.
	YggdrasilNodesTable = &schema.Table{
		Name:       "yggdrasil_nodes",
		Columns:    YggdrasilNodesColumns,
		PrimaryKey: []*schema.Column{YggdrasilNodesColumns[0]},
	}
	// YggdrasilNodeNeighborsColumns holds the columns for the "yggdrasil_node_neighbors" table.
	YggdrasilNodeNeighborsColumns = []*schema.Column{
		{Name: "yggdrasil_node_id", Type: field.TypeInt},
		{Name: "neighbor_id", Type: field.TypeInt},
	}
	// YggdrasilNodeNeighborsTable holds the schema information for the "yggdrasil_node_neighbors" table.
	YggdrasilNodeNeighborsTable = &schema.Table{
		Name:       "yggdrasil_node_neighbors",
		Columns:    YggdrasilNodeNeighborsColumns,
		PrimaryKey: []*schema.Column{YggdrasilNodeNeighborsColumns[0], YggdrasilNodeNeighborsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "yggdrasil_node_neighbors_yggdrasil_node_id",
				Columns:    []*schema.Column{YggdrasilNodeNeighborsColumns[0]},
				RefColumns: []*schema.Column{YggdrasilNodesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "yggdrasil_node_neighbors_neighbor_id",
				Columns:    []*schema.Column{YggdrasilNodeNeighborsColumns[1]},
				RefColumns: []*schema.Column{YggdrasilNodesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		YggdrasilNodesTable,
		YggdrasilNodeNeighborsTable,
	}
)

func init() {
	YggdrasilNodeNeighborsTable.ForeignKeys[0].RefTable = YggdrasilNodesTable
	YggdrasilNodeNeighborsTable.ForeignKeys[1].RefTable = YggdrasilNodesTable
}
