openapi: '3.0.2'
info:
  title: yggmap
  version: '1.0'
paths:
  /api/v1/nodes:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Node"
  /api/v1/nodes/active:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Node"
  /api/v1/network/current:
    get:
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NetworkGraph"
  
components:
  schemas:
    Node:
      type: object
      properties:
        publicKey:
          type: string
        coordinates:
          type: array
          items:
            type: number
            format: int32
        additionalInfo:
          type: object
    NetworkGraph:
      type: object
      properties:
        nodes:
          type: array
          items:
            $ref: "#/components/schemas/Node"
        links:
          type: array
          items:
            $ref: "#/components/schemas/NetworkLink"
    NetworkLink:
      type: object
      properties:
        key1:
          type: string
        key2:
          type: string
