name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run gqlgen
        run: go run github.com/99designs/gqlgen@v0.17.45 generate

      - name: Build
        run: go build -v ./cmd/crawler/

      - name: Test
        run: go test -v ./...
